# Generated by Django 4.1.2 on 2022-10-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
